### your site title here

title: Mourjo Sen
baseurl:  # name of the repository
email: mourjo@mourjo.me



highlighter: rouge
markdown: kramdown


paginate: 4


# Tracker
analytics: UA-83979082-4

# Comments
disqus-shortname: mourjo


#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []


sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md


plugins:
  - jekyll-seo-tag
  - jekyll-paginate
